DROP TABLE IF EXISTS Books;

CREATE TABLE Books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER,
  publisher_id INTEGER,
  title VARCHAR,
  genre VARCHAR,
  released_on DATE,
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL,
  FOREIGN KEY (author_id) REFERENCES Authors(id),
  FOREIGN KEY (publisher_id) REFERENCES Publishers (id)
);

DROP TABLE IF EXISTS Authors;

CREATE TABLE Authors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  publisher_id INTEGER DEFAULT NULL,
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL,
  FOREIGN KEY (publisher_id) REFERENCES Publishers (id)
);

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR DEFAULT NULL,
  email VARCHAR DEFAULT NULL,
  password VARCHAR DEFAULT NULL,
  username VARCHAR DEFAULT NULL,
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL
);

DROP TABLE IF EXISTS Publishers;

CREATE TABLE Publishers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR DEFAULT NULL,
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL
);

DROP TABLE IF EXISTS Reviews;

CREATE TABLE Reviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  book_id INTEGER DEFAULT NULL,
  user_id INTEGER DEFAULT NULL,
  rating INTEGER DEFAULT NULL,
  content VARCHAR DEFAULT NULL,
  updated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL,
  FOREIGN KEY (book_id) REFERENCES Books (id),
  FOREIGN KEY (user_id) REFERENCES Users (id)
);
